### ISSUE TITLE
The environment

### ISSUE THREAD

**Issue by JurinJC** [RobinMagnet/ReversibleHarmonicMaps#1]
hello, when I run the test, it will crash
```
mesh1 = TriMesh('D:\ReversibleHarmonicMaps\examples\data\mesh1.off', area_normalize=True, center=True).process(k=50, intrinsic=True)
mesh2 = TriMesh('D:\ReversibleHarmonicMaps\examples\data\mesh2.off', area_normalize=True, center=True).process(k=50, intrinsic=True)
```
If i remove the process or set the` intrinsic = False`, it will continue to execute the following, but pykeops will crash.
```
Traceback (most recent call last):
  File "D:\keops\test\test_keopscore.py", line 15, in <module>
    pykeops.test_numpy_bindings()
  File "d:\keops\pykeops\pykeops\numpy\test_install.py", line 20, in test_numpy_bindings
    if np.allclose(my_conv(x, y).flatten(), expected_res):
  File "d:\keops\pykeops\pykeops\numpy\generic\generic_red.py", line 347, in __call__
    out = self.myconv.genred_numpy(-1, ranges, nx, ny, nbatchdims, out, *args)
  File "d:\keops\pykeops\pykeops\common\keops_io\LoadKeOps.py", line 230, in genred
    self.call_keops(nx, ny)
  File "d:\keops\pykeops\pykeops\common\keops_io\LoadKeOps_nvrtc.py", line 42, in call_keops
    self.launch_keops(
RuntimeError: [KeOps] Cuda error.
```
My environment is following: 
```
WIndow11
cuda 12.1
torch 2.3.1 + cu121
```

**Comment by RobinMagnet** [comment]
Hi,
This looks like an issue with your installation of pykeops.

You should check again the [installation page](https://www.kernel-operations.io/keops/python/installation.html), and then [test your installation](https://www.kernel-operations.io/keops/python/installation.html#testing-your-installation).

Hope you'll find a solution there.
